// This file is generated by Slice Machine. Update with care!

import HeroBanner from './HeroBanner';
import Image from './Image';
import Introduction from './Introduction';
import ScreenshotGallery from './ScreenshotGallery';

export {
	HeroBanner,
	Image,
	Introduction,
	ScreenshotGallery,
};

export const components = {
	hero_banner: HeroBanner,
	image: Image,
	introduction: Introduction,
	screenshot_gallery: ScreenshotGallery,
};
